### ISSUE TITLE
Foreign news sites are being incorrectly parsed

### ISSUE THREAD

**Issue by joecoolish** [ndaidong/article-parser#102]
Trying to parse articles from news sites like [Almasirah](http://www.almasirah.net/) result in the related links being pulled in as the content, instead of the actual content.

Use as an example this article: http://www.almasirah.net/details.php?es_id=32771&cat_id=4

**Comment by ndaidong** [comment]
@joecoolish thank you for your feedback. I've checked and already found the cause here. A new patch version will be released asap to fix this.

**Comment by ndaidong** [comment]
@joecoolish I believe that v4.1.0 can extract the article from Almasirah and similar sites as well now. 

![Screenshot_2019-12-03_16-11-40](https://user-images.githubusercontent.com/1809619/70036700-e1508280-15e7-11ea-95e0-7531199a31da.png)

**Comment by joecoolish** [comment]
Thank you for the quick turn-around!  Looks great!
