### ISSUE TITLE
Extraction failed when URL terminates with slash " / " character 

### ISSUE THREAD

**Issue by nnnnicholas** [ndaidong/article-parser#107]
I noticed that article-parser fails when parsing URLs ending in `/`.

For instance, article-parser succeeds with 
`https://knightcolumbia.org/content/tim-wu-first-amendment-obsolete `
but fails with 
`https://knightcolumbia.org/content/tim-wu-first-amendment-obsolete/`

Perhaps this is expected behavior.

**Comment by ndaidong** [comment]
@nnnnicholas article-parser use `node-fetch` to retrieve content from target URL, as same as what the web browsers do. If you try to open these 2 URLs with your browser, you can see that they are totally different. 

Resolving the slash at the end of the URLs is the task of web server, not client.

**Comment by nnnnicholas** [comment]
Ah, true. Thank you.
