### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by jordyamc** [ndaidong/article-parser#112]
Hi! i get null object whet running parser in this [link](https:/re-library.com/2020/05/03/life-with-a-tail-chapter-32/)

**Comment by ndaidong** [comment]
@jordyamc your link leads me to a 404 page from GitHub

![Screenshot from 2020-05-04 16-28-47](https://user-images.githubusercontent.com/1809619/80952798-715b5800-8e24-11ea-89b0-bbe9f9938cb8.png)

**Comment by jordyamc** [comment]
What? Github added a github.com at the start

[https://re-library.com/2020/05/03/life-with-a-tail-chapter-32/](https://re-library.com/2020/05/03/life-with-a-tail-chapter-32/)

**Comment by ndaidong** [comment]
@jordyamc the correct URL may be:

https://re-library.com/translations/life-with-a-tail/volume-1/chapter-32-almighty-dragon-type-ultimate-weapon-still-a-nudist/

It can be extracted as well:

https://us-central1-technews-251304.cloudfunctions.net/article-parser?url=https://re-library.com/translations/life-with-a-tail/volume-1/chapter-32-almighty-dragon-type-ultimate-weapon-still-a-nudist/

As I tested on several browsers, there is no article content at your link:

![Screenshot from 2020-05-05 13-10-09](https://user-images.githubusercontent.com/1809619/81039205-8b537400-8ed2-11ea-8367-65348e76f16d.png)
