### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by shyamal890** [ndaidong/article-parser#117]
https://www.smarttask.io/blog/business-impact-analysis

**Comment by ndaidong** [comment]
@shyamal890 if you view source of this link, you can see smarttask does not render its article content by regular way, but loads the content into JavaScript/JSON and then uses script to display (find `<script id="smarttask-state" type="application/json">` tag).

I guess that they want to protect their high-price content from the crawlers/spiders and the tools like `article-parser`.

**Comment by shyamal890** [comment]
Actually, it displays the data after the page is rendered on the client. If you wait for like 1-2 secs the data would have been rendered and the parser would be able to extract the article details. 

Is there an option to wait for a few seconds before the parser runs?

**Comment by ndaidong** [comment]
@shyamal890 no, it's rendered with JavaScript. Currently `article-parser` does not support parse content generated by client script yet.
