### ISSUE TITLE
Feature Request: Extracting Link details

### ISSUE THREAD

**Issue by shyamal890** [ndaidong/article-parser#119]
It would be interesting to get data like whether the link is a `do-follow` or `no-follow`.

**Comment by ndaidong** [comment]
@shyamal890 Is that actually necessary? Personally I only care about if the content from that link has been extracted or not.

**Comment by shyamal890** [comment]
Yes, this would be very useful for digital marketers tracking if a link is dofollow or not.

 
 
  On Fri, 29 May 2020 at 2:25 pm, Dong Nguyen<notifications@github.com> wrote:   


@shyamal890 Is that actually necessary? Personally I only care about if the content from that link has been extracted or not.

**Comment by ndaidong** [comment]
@shyamal890 ok, I will consider how to implement this feature. Thanks for your idea.

**Comment by shyamal890** [comment]
Hi @ndaidong was this addressed in recent release?
