### ISSUE TITLE
Feature Request: Favicon

### ISSUE THREAD

**Issue by castroCrea** [ndaidong/article-parser#120]
Hello,
First I want to say that your lib is ✨greate.

What would you think about adding the favicon of the page, is will allow to add a nice title of the article ?!

Have a good day

**Comment by ndaidong** [comment]
@castroCrea thank you for your compliment.

Regarding favicon, I think it's "good to have" feature but not "must have". For right now you can get article favicon with Google S2. Just give it a domain to the whole URL, it will provide you the favicon to display on your view.

https://www.google.com/s2/favicons?domain=www.facebook.com
https://www.google.com/s2/favicons?domain=https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension
