### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by paulakfleck** [ndaidong/article-parser#121]
Url: https://www.bloomberg.com/news/articles/2016-05-24/as-zenefits-stumbles-gusto-goes-head-on-by-selling-insurance

**Comment by paulakfleck** [comment]
Even tho, now thinking about it, I think they want to avoid these kind of tools since the article is under a pay wall. But let me know your thoughts.

**Comment by ndaidong** [comment]
@paulakfleck thank you. At my very first look, this website requires reader to be Bloomberg News subsriber. Otherwise, it will show just a part of article.
