### ISSUE TITLE
Issue while importing package.

### ISSUE THREAD

**Issue by koundinya** [ndaidong/article-parser#122]
Got the following exception when I import the package,

```
TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<DataView>'
```

I think the issue is with `sanitize-html` 

Node Version - `v12.18.0` 

Does any one else have the same issue?

**Comment by ndaidong** [comment]
@koundinya thank you for your feedback. What environment you are trying to import it on? Node.js or client side with builder tools?

**Comment by koundinya** [comment]
Thank you for replying @ndaidong  :) 
Node.js for a server app I am building. I am also not using any framework like express, if that helps.

**Comment by ndaidong** [comment]
> Thank you for replying @ndaidong :)
> Node.js for a server app I am building. I am also not using any framework like express, if that helps.
It's better if you share your code :)
 I could not reproduce the issue as you got. I've also checked sanitize-html source code but it seems there is nothing relating to `<DataView>`.

**Comment by koundinya** [comment]
You were right, there was an issue with a Dockerfile and it wasn't an issue with the library. Thank you for the library 👏
