### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by michaelfarrell76** [ndaidong/article-parser#123]
This package is really nice and has a simple api compared to some alternatives out there. Would be awesome if typescript types were included!

**Comment by ndaidong** [comment]
@michaelfarrell76 I have a plan to build another version that works on deno. That might be the time to convert the source code to TS.

**Comment by CalvinTp** [comment]
Agree that this is a nice package, do you have any updates to have this package to work in typescript?

**Comment by stellis** [comment]
@ndaidong You can add TypeScript types without converting the code. It seems like the API is fairly simple, so it probably wouldn't take more than an hour.

**Comment by ndaidong** [comment]
@CalvinTp @stellis thank you for mentioning. I almost forgot this issue. As @stellis suggestion, I will try to add types in the next release.

**Comment by ndaidong** [comment]
@michaelfarrell76  @CalvinTp @stellis hello, could you help me check [article-parser@4.2.4-rc1](https://www.npmjs.com/package/article-parser/v/4.2.4-rc1) to see if type works? Thanks.

**Comment by ndaidong** [comment]
Hi there. I would like to close this issue after  v4.2.5 release. Feel free to reopen if any other problem. Thanks.

**Comment by CalvinTp** [comment]
Thanks for the update, sorry for the delay as I was tied up the last 2 days. I would update as soon as I have tested this and would also re-open if i see any issues. Thanks!

**Comment by CalvinTp** [comment]
@ndaidong , i just checked the new released, it is working without an issue! 👍 Thanks!!

**Comment by ndaidong** [comment]
@CalvinTp thank you for your confirmation :)
