### ISSUE TITLE
Null when extracting article

### ISSUE THREAD

**Issue by mosesweb** [ndaidong/article-parser#127]
Hello! 

Suddenly I have encountered problems when using article-parser. I get NULL from when using extract but it works when inputting the URL into the demo of your application at https://ndaidong.github.io/article-parser-demo/. I have the following code: 
```
const url = 'https://news.yahoo.co.jp/articles/5c75721b1d2afe89beaf2a7f81e2bcff961fc56a';
  extract(url).then((article) => {
    console.log(article);
    res.json(article);

  }).catch((err) => {
    console.log(err);
    res.json(err);
  });
```

(Using express). What can be the issue here? Other sites works. I guess I've parsed too much from Yahoo and got blocked or something?

**Comment by ndaidong** [comment]
@mosesweb thank you, I've just reformat the code in your question for easier reading.

Which version of article-parser are you using?

**Comment by mosesweb** [comment]
I am using the latest version of article-parser. Hmm, maybe it could be something with the language. Japanese ones are the articles I want to parse. I have tried different articles from Yahoo News and sometimes it works and sometimes not. Not sure where to go from here. I could try downgrade.

**Comment by ndaidong** [comment]
@mosesweb The demo sends url to Google Cloud Function where I run an express server script as same as what you have wrote. However it was set up with v4.2.1, not latest.

![Screenshot from 2020-07-30 15-51-26](https://user-images.githubusercontent.com/1809619/88902558-940ed880-d27c-11ea-8e8b-eaa12a65403c.png)

**Comment by mosesweb** [comment]
Thank you for the information, that could be this issue indeed!
