### ISSUE TITLE
Extracting from Full HTML does not work

### ISSUE THREAD

**Issue by georgjaehnig** [ndaidong/article-parser#128]
Hi, I understand that I can use `extract()` also by passing a string containing a full HTML page

    extract(String url | String html)

Yet if I do this, I get `null` as a return. Take the contents of  http://mindingourway.com/half-assing-it-with-everything-youve-got/ as an example. Passing the URL works fine, but reading the URL contents into a string and then passing the string to `extract()` fails.

A little bit of debugging `article-parser` leads to the finding that the culprit is `isHtmlDoc(input)`. This function only returns `true` if there's at least 10 `<div>` tags in the string:

    return htmlTags === 1 && headTags === 1 && bodyTags === 1 && divTags > 10;

I don't think that's a good heuristic. ;)

Why not skipping `isHtmlDoc()` at all and simply checking if the string begins with a `<`?

**Comment by ndaidong** [comment]
@georgjaehnig thank you for your opinion. You're right. We can render web pages without using DIV tags so that is not correct rule. I will remove this condition.

**Comment by ndaidong** [comment]
@georgjaehnig this issue has been resolved with v4.2.3, hope that helps.
