### ISSUE TITLE
Cannot find module htmlparser2/lib/Parser.js on Runkit

### ISSUE THREAD

**Issue by onigetoc** [ndaidong/article-parser#139]
I tryed it on Runkit and it said: Cannot find module 'htmlparser2/lib/Parser.js'

https://runkit.com/onigetoc/5fbdc488c98cad001a2f7923
OR
https://npm.runkit.com/article-parser

**Comment by ganeshmani** [comment]
Facing the same problem. `htmlparser2` is missing in the dependency as well.

<img width="1065" alt="Screenshot 2020-12-12 at 2 37 02 PM" src="https://user-images.githubusercontent.com/17050715/101979946-8126fe80-3c87-11eb-90a5-cbb5f1f28265.png">

**Comment by ndaidong** [comment]
@ganeshmani @onigetoc thank you for your feedback. The problem might relate to [readabilitySAX](https://github.com/fb55/readabilitySAX) and its own dependency [htmlparser2](https://github.com/fb55/htmlparser2). I will take a look into the root cause here.

**Comment by ganeshmani** [comment]
@onigetoc  i fixed it, can i raise a PR?

**Comment by ndaidong** [comment]
@ganeshmani yes, of course. Thank you for your contribution.

**Comment by hennaken** [comment]
Is the pull request done yet?

**Comment by ndaidong** [comment]
@onigetoc hello, could you make a pr?

**Comment by ndaidong** [comment]
Fixed since v4.2.6 (#144) with pr #142 by @ganeshmani
