### ISSUE TITLE
Expected to return a value at the end of async arrow function  consistent-return

### ISSUE THREAD

**Issue by niamao** [ndaidong/article-parser#140]
Why do I get this error?  Can someone please help me?

"Expected to return a value at the end of async arrow function  consistent-return."

I use it on an onChange since I would like the URL put in the input to be used.

const handleChange = async (event) => {
    try {
      const article = await extract(event.target.value)
      return article
    } catch (err) {
      console.trace(err)
    }
  }

**Comment by ndaidong** [comment]
@niamao it seems your handler only returns value in the case everything work well, and returns nothing when there is error occurs.
Try this:

```js
const handleChange = async (event) => {
  try {
    const article = await extract(event.target.value)
    return article
  } catch (err) {
    console.trace(err)
  }
  return null;
}
```
