### ISSUE TITLE
Content without markup

### ISSUE THREAD

**Issue by surjitsinghbhachu** [ndaidong/article-parser#145]
Is there a way to get the content without markup (i.e. plain text) or would you recommend another library to do this?

**Comment by ndaidong** [comment]
@surjitsinghbhachu do you mean removing html tags? If so, you just need a small function like [this one](https://github.com/ndaidong/bellajs/blob/main/src/utils/string.js#L43).

**Comment by surjitsinghbhachu** [comment]
Great thanks I'll use that for now. For a feature request, It might be good to have both a contentHtml and content attribute (removed html tags) so it can be used for textual processing.

**Comment by ndaidong** [comment]
Thank you. IMHO, removing HTML tags should be the first step of the text normalization process. However, I will close this issue while considering your suggestion.
