### ISSUE TITLE
typeError fs.readFileSync is not a function

### ISSUE THREAD

**Issue by heresy0-0y** [ndaidong/article-parser#146]
```
  144555 | exports.FILES = [/*require.resolve*/(/*! ../lib/utils.js */ "./node_modules/uglify-js/lib/utils.js"), /*require.resolve*/(/*! ../lib/ast.js */ "./node_modules/uglify-js/lib/ast.js"), /*require.resolve*/(/*! ../lib/transform.js */ "./node_modules/uglify-js/lib/transform.js"), /*require.resolve*/(/*! ../lib/parse.js */ "./node_modules/uglify-js/lib/parse.js"), /*require.resolve*/(/*! ../lib/scope.js */ "./node_modules/uglify-js/lib/scope.js"), /*require.resolve*/(/*! ../lib/compress.js */ "./node_modules/uglify-js/lib/compress.js"), /*require.resolve*/(/*! ../lib/output.js */ "./node_modules/uglify-js/lib/output.js"), /*require.resolve*/(/*! ../lib/sourcemap.js */ "./node_modules/uglify-js/lib/sourcemap.js"), /*require.resolve*/(/*! ../lib/mozilla-ast.js */ "./node_modules/uglify-js/lib/mozilla-ast.js"), /*require.resolve*/(/*! ../lib/propmangle.js */ "./node_modules/uglify-js/lib/propmangle.js"), /*require.resolve*/(/*! ../lib/minify.js */ "./node_modules/uglify-js/lib/minify.js"), /*require.resolve*/(/*! ./exports.js */ "./node_modules/uglify-js/tools/exports.js")];
  144556 | new Function("exports", function () {
  144557 |   var code = exports.FILES.map(function (file) {
> 144558 |     return fs.readFileSync(file, "utf8");
         |               ^  144559 |   });
  144560 |   code.push("exports.describe_ast = " + describe_ast.toString());
  144561 |   return code.join("\n\n");
```

**Comment by heresy0-0y** [comment]
btw, your demo is beautiful and i can't wait to get this running for my minimalist content-reader <3 !

**Comment by ndaidong** [comment]
@heresy0-0y where do you run your code? please share more info about your environment (os, nodejs version...).

**Comment by devinellis** [comment]
Hi, I am running into a similar issue trying to get article-parser to run within a Cloudflare Worker. They do not provide an `fs` module. Any way we can make this dependency optional?

**Comment by ndaidong** [comment]
@devinellis I'm not familiar with Cloudflare Worker. As my quick search, its environment is not Node.js, so you could not use Node.js module there.

https://community.cloudflare.com/t/cant-resolve-fs-in-cloudflare-workers/112762/4

**Comment by devinellis** [comment]
Some NPM modules will work, as long as they don't depend on some of the node-js native modules like fs. Their CLI has an option to shim globals via webpack, I might try that. But just doing a search for `fs`, other than in tests it only seems to be used in reset.js. Anyways was just piling onto the Issue, if there's an easy way to avoid node-specific modules it could open this up for wider use.

**Comment by ndaidong** [comment]
@devinellis note that `fs` is not only native module. `article-parser` also uses `url` module at some places. I just tried to create a Cloudflare Worker, and it does not understand `url` module too.
