### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by aviNrich** [ndaidong/article-parser#147]
Hi,
the following article was failed to fetch: https://www.oakridger.com/obituaries/story-obituaries-2021-01-25-thomas-howard-scott-4254755001
this is not a single page app...  
Thanks

**Comment by ndaidong** [comment]
@aviNrich the way this website was built is quite strange. It includes 2 iframes for header and footer. Other parts are stored as a Redux state object in a pair of `<script id="__NEXT_DATA__" type="application/json"></script>` tags, those are being rendered with JavaScript.

**Comment by aviNrich** [comment]
Ok, thanks
