### ISSUE TITLE
WallStreetJournal (wsj.com), extraction failure

### ISSUE THREAD

**Issue by cayolblake** [ndaidong/article-parser#148]
Hello,

Awesome project btw!

Extraction includes lots of non-article body content along main article content, example is https://www.wsj.com/articles/robinhood-raises-another-2-4-billion-from-shareholders-11612197680

**Comment by cayolblake** [comment]
Similar behavior for this site as well https://defence-blog.com/news/huntington-ingalls-wins-175m-deal-to-support-u-s-navy-aircraft-carriers.html

**Comment by ndaidong** [comment]
@cayolblake I think we can deal with defence-blog.com but there is a challenge with wsj.com because they require to login/subscribe to see the whole article.

**Comment by ndaidong** [comment]
Resolved with a little rule in v4.2.7
