### ISSUE TITLE
URL not working with version 4.2.6 while working only with 3.0.0 and not any later version

### ISSUE THREAD

**Issue by cayolblake** [ndaidong/article-parser#149]
Hello,

The following URL been working fine all day extracting info, it appears some change occurred to the page on their end then it completely stopped working returning null each time I attempt to extract data from it. 

Other URLs from the same site works fine without problems.

I started trying all versions down to version 3.0.0 which is the only version that currently works for some reason!

URL -> https://www.aljazeera.com/news/2021/2/3/myanmar-police-file-charges-against-suu-kyi-says-document

Not sure if I'm doing anything wrong, I stripped my code down to the provided example to be sure before reporting.

**Comment by ndaidong** [comment]
@cayolblake thank you, I will check it asap.

**Comment by ndaidong** [comment]
Resolved with a little rule in v4.2.7
