### ISSUE TITLE
(thebureauinvestigates.com), partial extraction only

### ISSUE THREAD

**Issue by cayolblake** [ndaidong/article-parser#150]
Hello,

This site appears to be using some sort of simple separator that to separate the full article body, resulting in extraction working only on the first part of the article and leaving out the rest while still extracting the very last line at the end of the whole article.

Example, https://www.thebureauinvestigates.com/stories/2020-11-25/imprisoned-under-the-cover-of-covid

Version: 3.0.0

**Comment by cayolblake** [comment]
Well, trying with version 4.2.6 results in failure to extract the article properly and instead extracted almost everything from the page.

It's the fourth or fifth time to see version 3.0.0 outperform 4.2.6.

**Comment by ndaidong** [comment]
@cayolblake yes, since v4.0.0 we've changed parser engine from `es6-readability` to `readabilitySAX`. It's better in general, especially with the websites those follow the standard structure. But some websites such as thebureauinvestiagetes.com may be particular.

**Comment by ndaidong** [comment]
@cayolblake resolved with v4.2.7, please reopen if any other issue. Thanks.
