### ISSUE TITLE
Working example for setting options

### ISSUE THREAD

**Issue by cayolblake** [ndaidong/article-parser#151]
Hello,

Is it possible to provide a working example for customizing user agent and allowed html tags?

**Comment by ndaidong** [comment]
@cayolblake ok, I will try.

**Comment by cayolblake** [comment]
Hello,

Had the time to look at this :) ?

**Comment by ndaidong** [comment]
@cayolblake sorry, we are in the most important holiday in Vietnam :D

**Comment by cayolblake** [comment]
Oh, happy holidays 8-)

**Comment by ndaidong** [comment]
@cayolblake actually they are already in the test script:

Custom fetch options:
https://github.com/ndaidong/article-parser/blob/v4.2.7/src/main.test.js#L141

Custom allowed  tags:
https://github.com/ndaidong/article-parser/blob/v4.2.7/src/main.test.js#L151

Is that enough for you?

**Comment by ndaidong** [comment]
@cayolblake please refer the test script here:

Custom user agent:
https://github.com/ndaidong/article-parser/blob/main/src/main.test.js#L150

Custom allowed tags:
https://github.com/ndaidong/article-parser/blob/main/src/main.test.js#L171

Let's me know if that is enough for your situation. Thanks.
