### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by ShepDogSk** [ndaidong/article-parser#157]
Hi, this url 

https://hnonline.sk/svet/2306911-zufala-doba-si-ziada-zufale-ciny-krajina-je-ochotna-za-vakciny-menit-aj-zdravotnikov

not scrapet.

Error in html-minifier. This package updated 2 years ago . Would it be better to use another minifier ?  For example minify ?

**Comment by ndaidong** [comment]
@ShepDogSk thank you, I will try to replace it.

**Comment by ndaidong** [comment]
@ShepDogSk the content from hnonline.sk doesn't show entirely by default, so `article-parser` could not extract. The cause does not relate to `html-minifier`.

However I've replaced `html-minifier` with [html-minifier-terser](https://github.com/terser/html-minifier-terser) as better maintenance. 

Feel free to reopen if needed.
