### ISSUE TITLE
Fail import

### ISSUE THREAD

**Issue by MonkeyTiger** [ndaidong/article-parser#158]
import { extract } from 'article-pasrser';

'extract' is declared but its value is never read.ts(6133)

I get this error in typescript.

**Comment by ndaidong** [comment]
@MonkeyTiger where did you run this script?

**Comment by MonkeyTiger** [comment]
I use the electron app.
src/main/index.ts

This is an error.
Trace: TypeError: article_parser_1.extract is not a function

**Comment by ndaidong** [comment]
I'm not sure that it works within electron environment. This lib is only being tested on Node.js server.
