### ISSUE TITLE
Details on how project internally work

### ISSUE THREAD

**Issue by cayolblake** [ndaidong/article-parser#159]
Hello,

Would it be possible @ndaidong to write down how the project is structured and how it manages to accurately extract data, also how it compares to readability js.

**Comment by ndaidong** [comment]
@cayolblake hello, this lib was built on top of readability.js, with just a few additions for extracting meta data.

**Comment by cayolblake** [comment]
Oh I see, that's interesting.

I wonder why v3 latest is kind of more accurate than v4 latest since both depends on readability lib! 🤔
