### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by ikshitadg** [ndaidong/article-parser#161]
Extraction failed for this url----https://www.thehindu.com/news/national/other-states/rajasthan-launches-health-insurance-scheme-for-all/article34215577.ece, Can you fix it?

**Comment by ndaidong** [comment]
@ikshitadg as I tested with [the demo app](https://ndaidong.github.io/article-parser-demo/), this url is still being extracted sucessfully. But the result includes too much unrelevant content because that website's HTML structure is so bad. 

I have no idea to improve the result for right now.
