### ISSUE TITLE
Possibility to extract category/or classification from a url?

### ISSUE THREAD

**Issue by coturiv** [ndaidong/article-parser#162]
Hi @ndaidong , thanks for this awesome package.
Do you have a plan to extract category or classification from an article, such as politics, sports, technology, etc?

This is an example, and I can see them in the metadata.
https://www.foxnews.com/politics/biden-in-easter-message-calls-getting-vaccine-a-moral-obligation

![image](https://user-images.githubusercontent.com/5830587/113564905-b8f1f180-963c-11eb-843a-71d20733bf6a.png)

Thank you.

**Comment by ndaidong** [comment]
@coturiv I like to be able to get more userful information from the target urls. However, almost of the properties such as what you shared aren't standard yet. There is very few websites provide these values for us.

If you really need to classify the articles, I recommend a better approach: let's make use a little of AI. My good friends are [natural](https://www.npmjs.com/package/natural) and [brain.js](https://www.npmjs.com/package/brain.js). They are both lightweight,  simple, easy to apply to your program.
