### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by tangerine1202** [ndaidong/article-parser#164]
Hi, this article is failed to be parsed, can you fix it?

https://medium.com/act-as-a-software-engineer/git-workflow-%E5%96%84%E7%94%A8git%E5%88%86%E6%94%AF%E5%BC%B7%E5%8C%96%E5%B0%88%E6%A1%88%E7%9A%84%E9%96%8B%E7%99%BC%E6%B5%81%E7%A8%8B-c7af53da7b6e

**Comment by ndaidong** [comment]
@tangerine1202 this lib based on readability.js which its extraction algorithm only support english as well. I don't think that it works with other languages, especially the hieroglyphics.
