### ISSUE TITLE
Uncaught TypeError: fs.readFileSync is not a function in content script for chrome extension

### ISSUE THREAD

**Issue by MykolaSauliak** [ndaidong/article-parser#165]
STR:

1. install react-chrome-extension boilerplate
2. yarn add article-parser
3. add import {extract} from 'article-parser' to the content.js
4. build and run extension

actual: error with fs occurs
expected: successful import and usage of the library

![image](https://user-images.githubusercontent.com/16925900/115117995-e11d1100-9fa9-11eb-9cc1-ff8e9cb8c602.png)

**Comment by ndaidong** [comment]
@MykolaSauliak I'm sorry that `article-parser` works only within Node.js environment. Currently there is  no way to get it works on the browsers.
