### ISSUE TITLE
can't parse html content

### ISSUE THREAD

**Issue by imsasa** [ndaidong/article-parser#168]
https://github.com/ndaidong/article-parser/blob/ebe11911101020d249b9d5272d91ef8a5a318884/src/utils/parseFromHtml.js#L88

now,  extract method Can only receive url，if receive html will throw exception

**Comment by ndaidong** [comment]
@imsasa please refer this test script:

https://github.com/ndaidong/article-parser/blob/ebe11911101020d249b9d5272d91ef8a5a318884/src/main.test.js#L87

**Comment by imsasa** [comment]
> @imsasa please refer this test script:
> 
> https://github.com/ndaidong/article-parser/blob/ebe11911101020d249b9d5272d91ef8a5a318884/src/main.test.js#L87

not work……
can you explain why return null  when（!title || links.length === 0)
https://github.com/ndaidong/article-parser/blob/ebe11911101020d249b9d5272d91ef8a5a318884/src/utils/parseFromHtml.js#L74

**Comment by ndaidong** [comment]
@imsasa maybe a wrong logic here. I will take a look into this.
However the line 74 means if there is no title neither link detected, the function assumes that it has failed to extract.
