### ISSUE TITLE
Unable to parse published date

### ISSUE THREAD

**Issue by jasmedia** [ndaidong/article-parser#174]
Unable to parse publish dates on following articles:
https://www.chelseafc.com/en/news/2021/06/04/contract-extension-for-thomas-tuchel
https://ameyawdebrah.com/chelsea-star-callum-hudson-odoi-arrives-in-ghana-in-hangs-with-the-stars/
https://www.thehindu.com/entertainment/reviews/vakeel-saab-review-pawan-kalyan-amplifies-no-means-no/article34279888.ece?

**Comment by ndaidong** [comment]
@jasmedia we only get data time via meta tag  `article:published_time`. The sites you mentioned don't provide that value. The `thehindu.com` uses meta tag `publish-date` which is not standard.
