### ISSUE TITLE
String html is not available in extract()

### ISSUE THREAD

**Issue by Glowin** [ndaidong/article-parser#177]
I try to put html string as variable to extract, but not work.

**Comment by ndaidong** [comment]
@Glowin could you share your HTML string, as a HTML file?

**Comment by sateeshmohan** [comment]
I want to send html and get the result, is that possible?

**Comment by ndaidong** [comment]
@sateeshmohan yes, you can pass URL or HTML string to [extract](https://github.com/ndaidong/article-parser#extractstring-url--string-html) method

**Comment by sateeshmohan** [comment]
const {
    extract
} = require('article-parser');

const url = 'https://goo.gl/MV8Tkh';
const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>hello world</p>
</body>
</html>`
extract(html).then((article) => {
    console.log(article);
}).catch((err) => {
    console.log(err);
});
I try to pass html and got **null**

**Comment by ndaidong** [comment]
@sateeshmohan `html` string must be full HTML content of the web page (what you get when "View page source")

**Comment by sateeshmohan** [comment]
https://recruiting.ultipro.com/FOO1002FOAS/JobBoard/0aa79538-a07d-4367-be26-b4d4e53944e8/OpportunityDetail?opportunityId=0eae96b8-372a-46bd-9ce8-058a87361fee

this is not working for me

**Comment by ndaidong** [comment]
@sateeshmohan yes, because that page is rendered with JavaScript at client side. `article-parser` only works with pure HTML content (server side rendering).
