### ISSUE TITLE
Add ability to replace lazy pictures with original ones

### ISSUE THREAD

**Issue by yakimka** [ndaidong/article-parser#181]
Many sites uses lazy loading for images - low quality image in the `src` tag and original in `data-src`.  Example:
https://habr.com/ru/company/skillfactory/blog/566194/
```html
<img src="https://habrastorage.org/r/w780q1/getpro/habr/upload_files/dc4/d6f/536/dc4d6f5364abec4717e668e6b2f838d2.jpeg" alt="" title="" width="900" height="600" data-src="https://habrastorage.org/getpro/habr/upload_files/dc4/d6f/536/dc4d6f5364abec4717e668e6b2f838d2.jpeg" data-blurred="true"/>
```
Lazy image: https://hsto.org/r/w780q1/getpro/habr/upload_files/dc4/d6f/536/dc4d6f5364abec4717e668e6b2f838d2.jpeg
Original image: https://habrastorage.org/getpro/habr/upload_files/dc4/d6f/536/dc4d6f5364abec4717e668e6b2f838d2.jpeg

It seems to me that we need to replace images when parsing with original ones.

**Comment by ndaidong** [comment]
@yakimka cool! I will merge this pr now.
