### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by geekpulp** [ndaidong/article-parser#189]
Hi Team,

when I try to parse this url https://onewheel.com/products/onewheel-pint-x the returned value is null. Any idea why?

**Comment by ndaidong** [comment]
@geekpulp sorry this parser can only extract the particular structured data such as blog post or news entry. For regular web page, you may need to use the stronger engines.

**Comment by ndaidong** [comment]
Resolved since v5.0.0rc1
