### ISSUE TITLE
custom cookie's

### ISSUE THREAD

**Issue by RubenNL** [ndaidong/article-parser#20]
hello all,

i have a problem with this url: 'http://www.ad.nl/binnenland/toch-giftige-chroom-6-in-navo-opslag-almelo~ad630607'

you need to click on the accept cookie's button.
i have already made a script that generates a cookie that skips the check, but i cant find how i can use that here.
![image](https://cloud.githubusercontent.com/assets/15885455/20786204/e1e56b24-b7a4-11e6-8284-155e0e49153b.png)
here you can see the button, if the url doesnt work.
its an dutch newspaper.

**Comment by ndaidong** [comment]
@RubenNL thanks, this issue may be resolve with cookie jar, I guess that. 
Currently, you can get it works for this site by adding the domain "ad.nl" to exception list. Something like below:

```
ArticleParser.configure({
  exceptDomain: [
     'ad.nl',
    'nytimes.com',
    'sfgate.com',
    'theverge.com'
  ],
  EmbedlyKey: YOUR_EMBEDLY_KEY
});
```

Any URL in the list of _exceptDomain_ will be parsed with Embedly service.
