### ISSUE TITLE
Trying to extract text from some websites makes everything hang for almost a minute.

### ISSUE THREAD

**Issue by eamon0989** [ndaidong/article-parser#207]
In general it works extremelly well, but with urls from certain websites it just hangs for up to a minute.

You can reproduce the bug on your website here:
https://demos.pwshub.com/article-parser

With this link:
https://www.jw.org/fr/biblioth%C3%A8que/revues/reveillez-vous-no4-2016-aout/habitude/

Is there some way to set a timeout so that if it doesn't finish within say 2 seconds, it will return null or an error?

**Comment by ndaidong** [comment]
@eamon0989 thank you. It looks like the time to wait for response is over. 

![Screenshot from 2022-01-14 21-56-26](https://user-images.githubusercontent.com/1809619/149536256-5874cb52-f89b-4952-9aeb-a90d94af5b4a.png)

Tested with wget, it shows me as below:

![Screenshot from 2022-01-14 21-57-43](https://user-images.githubusercontent.com/1809619/149536377-6384070e-280e-4260-b8c6-64456fb290a2.png)
