### ISSUE TITLE
Using article-parser within TS project - not building CJS version after install

### ISSUE THREAD

**Issue by larryhudson** [ndaidong/article-parser#225]
Hi there, thanks for building this project.

I'm trying to use this within a TS project (the example repo provided by the CMS [Keystone](https://keystonejs.com/)).

I'm using Node v16.13.1 on macOS.

It should use the CJS version of article-parser, because the Keystone repo doesn't have 'type': 'module' in the package.json.

I get this error when trying to use it:

```
(node:17350) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/larryhudson/github.com/larryhudson/keystone-article-parser-test/node_modules/article-parser/package.json' of './dist/cjs/article-parser.js'. Please either fix that or report it to the module author
```

Looking in `node_modules/article-parser`, there is no dist folder, so I don't think article-parser is building the CJS version automatically after install. 

For it to work, I had to:
- `cd node_modules/article-parser`
- `npm install esbuild`
- `npm run build`

To reproduce this:
- clone this repo: https://github.com/larryhudson/keystone-article-parser-test
- `npm install`
- `npm run dev`

Thanks :-)

**Comment by ndaidong** [comment]
@larryhudson thank you, that's my mistake. `dist` folder should be commited.

**Comment by larryhudson** [comment]
Fantastic, thanks for fixing this so quickly. I've just updated to the new version and it's working now 🎉
