### ISSUE TITLE
Not a function

### ISSUE THREAD

**Issue by shivam-687** [ndaidong/article-parser#235]
"(t.getAttribute(...) || \"\").split is not a function"

**Comment by SettingDust** [comment]
Stacktrace

**Comment by andremacola** [comment]
@SettingDust try to eval this url `https://g1.globo.com/loterias/noticia/2022/03/19/mega-sena-pode-pagar-r-190-milhoes-neste-sabado-maior-valor-sorteado-no-ano.ghtml`

I think this is a problem with Mozilla Readability library

**Comment by andremacola** [comment]
I was debugging Mozilla Readability here: https://github.com/mozilla/readability/blob/1d2cb030b32e753cc4b7c4ce8b64c3ce4dc1b2ff/Readability.js#L334

```js
    for (node = node.firstElementChild; node; node = node.nextElementSibling) {
      const attr = node.getAttribute("class")
      console.log(attr, typeof attr)
      if (typeof attr !== 'object') {
        this._cleanClasses(node);
      }
    }

   // { baseVal: '', animVal: '' } object
```

And found that linkedom is setting `{ baseVal: '', animVal: '' }` and then Mozilla Readability crashes.

Look here:
https://github.com/WebReflection/linkedom/blob/2145416c314c5de23c1f1d87fa3b111db7253eaa/cjs/svg/element.js#L27

**Comment by andremacola** [comment]
Add SVG on unwanted array seems to solve the problem.

**Comment by SettingDust** [comment]
> I was debugging Mozilla Readability here

Different from the error `(t.getAttribute(...) || "").split`. Maybe another issue

**Comment by andremacola** [comment]
> > I was debugging Mozilla Readability here
> 
> ~Different from the error `(t.getAttribute(...) || "").split`. Maybe another issue~
> 
> MF. It is

What do you think is the best approach to solve this? I made a PR at [mozilla/readability](https://github.com/mozilla/readability) but I think we need to fix this here too.

**Comment by SettingDust** [comment]
I think linkedom should do something about this. Not us or Mozilla.

**Comment by SettingDust** [comment]
Well. Should be fixed by Readability, which I found to be part of the spec

**Comment by SettingDust** [comment]
Same conclusion. 
> I think linkedom should do something about this. Not us or Mozilla.

The `getAttribute` should return a string
