### ISSUE TITLE
Type for addQueryRules need to be fixed

### ISSUE THREAD

**Issue by andremacola** [ndaidong/article-parser#239]
Typescript for QueryRule do not match https://github.com/ndaidong/article-parser/blob/main/src/rules.js file

**Comment by SettingDust** [comment]
> Typescript for QueryRule do not match [https://github.com/ndaidong/article-parser/blob/main/src/rules.js](https://github.com/ndaidong/article-parser/blob/main/src/rules.js?rgh-link-date=2022-03-18T01%3A18%3A24Z) file

Where

**Comment by andremacola** [comment]
interface QueryRule at https://github.com/ndaidong/article-parser/blob/main/index.d.ts

**Comment by andremacola** [comment]
My bad. I was testing with the old pattern.
