### ISSUE TITLE
Be able to include multiple selectors

### ISSUE THREAD

**Issue by andremacola** [ndaidong/article-parser#248]
Mozilla Readability library is unable to parse the article sometimes and some big portals ***have different templates*** for some types of articles like special stories.

```
{
  ...
  selectors: ['.entry-article', '.article-content']
}
```

If the first selector doesn't find any content, it moves on to the next.

**Comment by SettingDust** [comment]
For example?
It seems to me that the different pages should be distinguished by URLPattern.

**Comment by andremacola** [comment]
If you work a lot with Wordpress websites heavily using Gutenberg custom blocks, the pages can have totally different markup with the same url pattern.

There could be Gutenberg blocks wrapping the article with classes like `class='.layout-with-right-sidebar'` or `class='.layout-with-left-sidebar'` unfortunately

Everything with the keyword `sidebar` is set to  `unlikelyCandidates ` by Mozilla Readability. See here: https://github.com/mozilla/readability/blob/1d2cb030b32e753cc4b7c4ce8b64c3ce4dc1b2ff/Readability-readerable.js#L26

Multiple selectors help to bypass that.

**Comment by SettingDust** [comment]
It's fine. Selector type to `string | string[]` for easier use.

**Comment by SettingDust** [comment]
Need to clarify the strategy of selectors. Combine all or pick the first?
