### ISSUE TITLE
Extract all images from article

### ISSUE THREAD

**Issue by andremacola** [ndaidong/article-parser#249]
Parse all <img> tags inside the article and return with an array of images

```
{
 ...
  title: the article title,
  images: ['https://domain.tld/image1.jpg', 'https://domain.tld/image2.jpg', 'https://domain.tld/image3.jpg']
}

**Comment by SettingDust** [comment]
This picture should be a banner. I think the pictures in the article should be part of the article. Extracting all images should be implemented in your own code.
