### ISSUE TITLE
removeLineBreaks causes inconsistency in text content spaces

### ISSUE THREAD

**Issue by andremacola** [ndaidong/article-parser#250]
With the option `removeLineBreaks: true`  in https://github.com/ndaidong/article-parser/blob/e0543954b4b00b5f7937a888754ebb395ed39d4a/src/utils/standalizeArticle.js#L39 the text spaces in many articles are replace with a `line break \n`. The words end up coming together (when not using a browser to display the result)

Here some screenshots examples with `yarn eval ./test-data/regular-article.html`

**1. removeLineBreaks: true**
<img width="715" alt="Captura de Tela 2022-03-25 às 01 27 09" src="https://user-images.githubusercontent.com/3408809/160054308-3316223b-f8b5-4765-ab35-def685e9c059.png">
<img width="597" alt="Captura de Tela 2022-03-25 às 01 35 05" src="https://user-images.githubusercontent.com/3408809/160054960-e8dad110-f5e4-4ef6-ac2b-06880c4504e3.png">

**2. removeLineBreaks: false**
<img width="1097" alt="Captura de Tela 2022-03-25 às 01 28 46" src="https://user-images.githubusercontent.com/3408809/160054416-b0317b6a-0f11-4402-9116-912406dfc7cf.png">
<img width="550" alt="Captura de Tela 2022-03-25 às 01 35 40" src="https://user-images.githubusercontent.com/3408809/160055011-8939f632-7f76-4b69-bfa1-fb2e41b28643.png">

I think we can do improve the sanitizer

**Comment by andremacola** [comment]
Related to: https://github.com/codsen/codsen/issues/3

**Comment by andremacola** [comment]
Maybe we can customize html-crush options with addQueryRules?

https://codsen.com/os/html-crush/#api-crush-optional-options-object

**Comment by SettingDust** [comment]
It's seems that is `lineLengthLimit`. Not `removeLineBreaks`

**Comment by andremacola** [comment]
Only `lineLengthLimit` does not solve all problems. If I want to extract only the paragraphs with it's line breaks to work with something else... Yes I can do with my own project code but the parser already have the tools for that.

Right now I'm doing something like that:

```
    removeHTMLComments: 2,
    removeLineBreaks: false,
    breakToTheLeftOf: ['<p', '<div', '<span', '<li'] // that's why maybe we can add to addQueryRules
```

**Comment by SettingDust** [comment]
> Only `lineLengthLimit` does not solve all problems. What If I want to extract only the paragraphs with it's line breaks to work with something else... Yes I can do with my own project code but the parser already have the tools for that.
> 
> Right now I'm doing something like that:
> 
> ```
>     removeHTMLComments: 2,
>     removeLineBreaks: false,
>     breakToTheLeftOf: ['<p', '<div', '<span', '<li'] // that's why maybe we can add to addQueryRules
> ```

I think the minize options should be a options that can be set just like `sanitizeHtmlOptions` or `requestOptions`. Not a part of rule

**Comment by andremacola** [comment]
> I think the minize options should be a options that can be set just like sanitizeHtmlOptions or requestOptions. Not a part of rule.

Agreed

> BTW, `removeLineBreaks` default if false

It's set to true when passing to crush options here: https://github.com/ndaidong/article-parser/blob/e0543954b4b00b5f7937a888754ebb395ed39d4a/src/utils/standalizeArticle.js#L39

**Comment by SettingDust** [comment]
> > I think the minize options should be a options that can be set just like sanitizeHtmlOptions or requestOptions. Not a part of rule.
> 
> Agreed
> 
> > BTW, `removeLineBreaks` default if false
> 
> It's set to true when passing to crush options here:
> 
> https://github.com/ndaidong/article-parser/blob/e0543954b4b00b5f7937a888754ebb395ed39d4a/src/utils/standalizeArticle.js#L39

It's should be true here. And the `breakToTheLeftOf` need `removeLineBreaks` true.

**Comment by SettingDust** [comment]
I can't find a reason for make the output html break the line with paragraphs. But add a method for set minize options is fine

**Comment by andremacola** [comment]
> I can't find a reason for make the output html break the line with paragraphs. But add a method for set minize options is fine

`breakToTheLeftOf` was only an example that I need for a personal project.

**Comment by SettingDust** [comment]
> removeLineBreaks in my opinion default should be false like html-crush defaults. But it's irrelevant if we have a way to customize with sanitizeHtmlOptions 

The output won't display to user. So it's fine in my mind.

**Comment by andremacola** [comment]
> Are you going to make it happen on your own? I don't know if I want to start

Yep, I can do that.
