### ISSUE TITLE
Unable to extract article data from YouTube url

### ISSUE THREAD

**Issue by pavancp0321** [ndaidong/article-parser#259]
Unable to extract article data from YouTube url

<img width="883" alt="image" src="https://user-images.githubusercontent.com/81090801/163229094-a27ea22d-e221-4657-8b47-e53ebb938279.png">

**Comment by ndaidong** [comment]
@pavancp0321 hello, this lib only focuses on text-based content such as blog entries, news entries... 
To extract YouTube link, you can use my another tool called [oembed-parser](https://github.com/ndaidong/oembed-parser).

**Comment by pavancp0321** [comment]
Thank you for the update.
