### ISSUE TITLE
Unable to extract articles from client-side rendering pages

### ISSUE THREAD

**Issue by Jiacheng787** [ndaidong/article-parser#260]
Some web pages need to execute JavaScript on the client side, load data from api call, and then render the page. Is it possible for this project to support these pages?

![image](https://user-images.githubusercontent.com/43509711/163298063-221f6345-3085-4ea7-9a37-79b513616205.png)

**Comment by ndaidong** [comment]
@Jiacheng787 hello, it's better to be able to extract content from client side rendering web apps.

However the content delivery systems which this library targets (mainly news sites, blogs) are all designed to be SEO-friendly and usually apply the SSR mechanism. I very rarely see any news site that works in the form of CSR.

Therefore, we have no plans to support this type of webapp at the moment.

**Comment by SettingDust** [comment]
Support of javascript will caused a lot performance loss. The JSDom or headless browser can do that. In my mind, you can get the page content with that by yourself, then call the `extract` function.

支持 JS 渲染会导致性能问题，你可以用 JSDOM 或者无头浏览器自己抓取页面渲染后的内容然后调用 `extract` 函数

**Comment by Jiacheng787** [comment]
Nice to get your replies, thanks.
