### ISSUE TITLE
how to make it like this web ?

### ISSUE THREAD

**Issue by mamasexeno** [ndaidong/article-parser#262]
how to make it like this https://extractor.pwshub.com/article/parse??
I've installed it on a web server, but I can't open it in a browser but I can do it on ssh.

how to implement so it's like the web https://extractor.pwshub.com/article/parse??

I use http.createServer in coding the js file also no results come out.
please help i'm a newbie.

is there an example file to implement on the web like this https://extractor.pwshub.com/article/parse ?

**Comment by ndaidong** [comment]
@mamasexeno hello, it's just a simple API built with expressjs. this guy can help you better than me:

- [How to Create your First API with Node and Express - part 1](https://www.youtube.com/watch?v=8Yq7k-ToD2U)
- [How to Create your First API with Node and Express - part 2](https://www.youtube.com/watch?v=p9o8_S1X8CM)

If you want to call to my api from your program, you can refer example by RapidAPI:

- https://rapidapi.com/pwshub-pwshub-default/api/article-extractor2/

**Comment by mamasexeno** [comment]
ok it's work for me. thanks for suggestion.
