### ISSUE TITLE
npm  start error

### ISSUE THREAD

**Issue by cxqeric** [ndaidong/article-parser#281]
after `npm  start`,
it show: 
`WARNING in ./node_modules/tldts-core/dist/es6/index.js
[1] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from 'D:\projectName\node_modules\tldts-core\index.ts' file: Error: ENOENT: no such file or directory, open 'D:\projectName\node_modules\tldts-core\index.ts'`

![image](https://user-images.githubusercontent.com/26587077/180114223-aae8f963-b3b2-4440-9fe5-2afdf54fcefe.png)

**Comment by ndaidong** [comment]
@cxqeric it seems you are working on TypeScript environment? Could you share a little more about your code?

**Comment by cxqeric** [comment]
> @cxqeric看来您正在使用 TypeScript 环境？你能分享更多关于你的代码的信息吗？

https://codesandbox.io/s/misty-dream-s4n38w?file=/src/index.js

![image](https://user-images.githubusercontent.com/26587077/180965162-4f65bb33-b5a7-4461-a2d7-07b85f36d481.png)

do you have a  successful demo?

**Comment by ndaidong** [comment]
@cxqeric thank you, it seems there is problem with some dependencies. When I download your project to test at local, the layout has been rendered but webpack threw error (relevant to `tldts-core@5.7.84`). This issue may need to be investigated more.

![Screenshot from 2022-07-26 18-47-34](https://user-images.githubusercontent.com/1809619/180999246-9ba3d195-7529-4cf5-9e05-7e17d2605bc0.png)
