### ISSUE TITLE
Parser extracting elements not visible in viewport

### ISSUE THREAD

**Issue by voxvici** [ndaidong/article-parser#282]
Hi,

If you try to parse the article https://www.arthritis.org/health-wellness/healthy-living/managing-pain/pain-relief-solutions/heat-therapy-helps-relax-stiff-joints you will get "Make a Donation", "Become a Member" etc elements that are not part of the article and are not visible in the viewport.

Is there a way to remove elements not visible in the viewport? thank you

**Comment by ndaidong** [comment]
@voxvici this page doesn't look like a regular article. However you can use [transformation](https://github.com/ndaidong/article-parser#transformations) to extract whatever you need from there.

For example, after looking into the content structure, I found that the main parts of content are placed within the `section` tags with class name `longformat` or `blockContent`, so I write a transformation as below:

```js
const tfmArthritis = {
  patterns: [
    '*://*.arthritis.org/*'
  ],
  pre: (document) => {
    const htmls = []
    document.querySelectorAll('section').forEach((element) => {
      if (element.classList.contains('longformat') || element.classList.contains('blockContent')) {
        htmls.push(element.innerHTML)
      }
    })
    document.body.innerHTML = htmls.join('')
    return document
  },
  post: (document) => {
    return document
  }
}
```

And use it as below:

```js
// write to file for test
import { writeFileSync } from 'fs'

import { addTransformations, extract } from 'article-parser'

addTransformations(tfmArthritis)

const outputFile = './output-test.html'
const url = 'https://www.arthritis.org/health-wellness/healthy-living/managing-pain/pain-relief-solutions/heat-therapy-helps-relax-stiff-joints'

extract(url).then((article) => {
  writeFileSync(outputFile, article.content, 'utf8')
})
```

Open `output-test.html` with your browser, you can see something like below:

![Screenshot from 2022-07-24 16-06-07](https://user-images.githubusercontent.com/1809619/180640313-5966cc7d-8ba7-48a5-aa9f-7ed1cb4ae4ac.png)

**Comment by voxvici** [comment]
appreciated! thank you for the explanation keep up the great work
