### ISSUE TITLE
App Crashing with fresh install

### ISSUE THREAD

**Issue by jlalvarez18** [ndaidong/article-parser#30]
I installed the module on my node app and get instant crashing.

``` node
var ArticleParser = require('article-parser')

function extractURL(url) {
    return ArticleParser.extract(url)
}
```

```
/.../node_modules/article-parser/src/main.js:15
14:13:17 worker.1 | var {configure, FETCH_OPTIONS} = config;
14:13:17 worker.1 |     ^
14:13:17 worker.1 | 
14:13:17 worker.1 | SyntaxError: Unexpected token {
14:13:17 worker.1 |     at exports.runInThisContext (vm.js:53:16)
14:13:17 worker.1 |     at Module._compile (module.js:404:25)
14:13:17 worker.1 |     at Object.Module._extensions..js (module.js:432:10)
14:13:17 worker.1 |     at Module.load (module.js:356:32)
14:13:17 worker.1 |     at Function.Module._load (module.js:311:12)
14:13:17 worker.1 |     at Module.require (module.js:366:17)
14:13:17 worker.1 |     at require (module.js:385:17)
14:13:17 worker.1 |     at Object.<anonymous> (/.../node_modules/article-parser/index.js:5:12)
14:13:17 worker.1 |     at Module._compile (module.js:425:26)
14:13:17 worker.1 |     at Object.Module._extensions..js (module.js:432:10)
```

Any thoughts? Thanks.

**Comment by jlalvarez18** [comment]
Same error even when testing in RunKit

https://runkit.com/npm/article-parser

**Comment by harryyuanfeng** [comment]
same here

**Comment by ndaidong** [comment]
@jlalvarez18 : could you show a little bit about your environment? OS, Node.js version, docker?  It may be version compatibility as @harryyuanfeng mentioned. This module only works with Node.js 6.0 and newer because it uses ES6 syntax.

**Comment by wasifale** [comment]
@ndaidong 

Is there any other way to use this module with ES5? 'cause I don't want to convert the whole app to ES6 for one module.

**Comment by wasifale** [comment]
I'm using Node v6.9.2 still getting the same error.

**Comment by ndaidong** [comment]
This is the time of ES7, you should rewrite it asap :)

However you can convert the whole code base of this module to ES5, using babel-cli, like below:

```
git clone https://github.com/ndaidong/article-parser.git
cd article-parser
npm install babel-cli babel-preset-env

// crearte .babelrc with nano
nano .babelrc
```

Add the following config to .babelrc

```
{
  "presets": ["env"]
}
```

Then now, start converting:

```
./node_modules/.bin/babel src -d output
```

If everything is ok, the CLI displays something like this:

![screenshot_2017-05-26_19-06-17](https://cloud.githubusercontent.com/assets/1809619/26493956/91ad9b0e-4246-11e7-9ba0-2168b62bef8d.png)

And you've got ES5 version of ArticleParser in ./output folder.
