### ISSUE TITLE
Fetch with proxy?

### ISSUE THREAD

**Issue by mpuz** [ndaidong/article-parser#304]
Having ability to pass proxy and custom headers to extract function would be great.

**Comment by ndaidong** [comment]
@mpuz do you mean something like this?

![Screenshot from 2022-09-21 09-23-24](https://user-images.githubusercontent.com/1809619/191400108-339aaa6a-5337-412d-8442-ca02cfea04dd.png)

**Comment by ndaidong** [comment]
@mpuz please check new parameter [fetchOptions](https://github.com/ndaidong/article-parser#fetchoptions-optional) to see if that's exactly what you need.

**Comment by mpuz** [comment]
> @mpuz please check new parameter [fetchOptions](https://github.com/ndaidong/article-parser#fetchoptions-optional) to see if that's exactly what you need.

Yes, thats it! thank You
Also I couldn't find how to prevent parser to remove all newline in the parsed text

**Comment by ndaidong** [comment]
@mpuz you are right, we should have an option to keep or remove newline.

**Comment by ndaidong** [comment]
@mpuz since v7.2.4, this lib only replaces multi lines with one linebreak, so we don't need a new option.

I'm considering how to allow user replace default fetch with proxied fetch which is modified by Proxy prototype.

**Comment by mpuz** [comment]
> @mpuz since v7.2.4, this lib only replaces multi lines with one linebreak, so we don't need a new option.
> 
> I'm considering how to allow user replace default fetch with proxied fetch which is modified by Proxy prototype.

I changed your code like this:

retrieve.js
```
// utils -> retrieve

import fetch from 'cross-fetch'

export default async (url, opts={}) => {
  const res = await fetch(url, {
    agent: opts?.agent || null,
    headers: {
      'user-agent': opts?.headers || 'Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0'
    }
  })
  const status = res.status
  if (status >= 400) {
    throw new Error(`Request failed with error code ${status}`)
  }
  const contentType = res.headers.get('content-type') || 'text/html'
  if (!contentType.includes('text/')) {
    throw new Error(`Content type must be "text/html", not "${contentType}"`)
  }
  return res.text()
}
```

And I use it like this

```
import { SocksProxyAgent } from 'socks-proxy-agent';

const proxyagent = new SocksProxyAgent(`socks://login:password@xx.xxx.xx.xxx:5500`);

const getArticle = async (artUrl) => {
    artUrl = artUrl.split('?')[0]
    let article = await artParser.extract(
        artUrl,
        {
         agent: proxyagent, 
         //headers: AGENTS[4]
        })
        .then((article) => {
        //console.log(article)
        return article
    }).catch((err) => {
        console.log(err, artUrl)
        return null
    })
    return article
}

```

**Comment by ndaidong** [comment]
@mpuz great, thank you for your suggestion. That works well on Node.js environment where we can take advantage of "Custom Agent" feature from `node-fetch`.
However it seems there is no `agent` option for native `fetch` prototype on the browsers and deno environment.

**Comment by Joel-PeakMetrics** [comment]
Hello, this proxy feature doesn't seem to work from Deno environments. Is there any plan for adding support for Deno?

https://deno.land/api@v1.37.0?unstable&s=Deno.createHttpClient

**Comment by ndaidong** [comment]
This lib supports 2 types of proxy, please refer [this section in README](https://github.com/extractus/article-extractor#fetchoptions-optional).

For Deno, we just have to wait until its `fetch` implementation is more complete.
