### ISSUE TITLE
Keep html element attributes on result.content And Incompleted result.content

### ISSUE THREAD

**Issue by dimaslanjaka** [ndaidong/article-parser#309]
**PROBLEM 1**
Keeping element attributes useful for filtering content, please add this feature

![image](https://user-images.githubusercontent.com/12471057/192507830-20ce9b12-26a0-4b25-87b0-5d82c47400aa.png)

wanna get element with these attributes, i dont want to include others (just partial elements)
![image](https://user-images.githubusercontent.com/12471057/192508075-33f1d4c0-6e3c-4f2b-9b5a-8c473c6069e7.png)

i saw https://github.com/ndaidong/article-parser#sanitize-htmls-options but i dont understand how to do it

the options says just allowed these properties
![image](https://user-images.githubusercontent.com/12471057/192512291-46a43b25-312d-439a-aee7-5740bdd8102f.png)

impossible to parsing with regex, because each page have different element structures
![image](https://user-images.githubusercontent.com/12471057/192514361-5721c4c1-7cbd-481a-8866-e88b63dd30dd.png)

need more examples

**PROBLEM 2**
the result from extracted content not completed.
some element inside article post removed automatically.
url to test: https://zilliongamer.com/chimeraland/c/guide/chimeraland-how-to-evolve-duahawk

original has these elements
![image](https://user-images.githubusercontent.com/12471057/192515342-659f024b-d207-4d21-8f9d-fe3760ca2c7a.png)

the result from `extract` just until here
![image](https://user-images.githubusercontent.com/12471057/192515405-8ae57830-b026-45b4-8fdf-ccba61c282cd.png)

**Comment by ndaidong** [comment]
@dimaslanjaka hello, I try to resolve few parts of your issue:

### Problem 1:

> Keeping element attributes useful for filtering content...

You can modify sanitize-html's options config a little bit. Here I get the default config, add expected attribute to `span` tag then update it back.

```js
import { getSanitizeHtmlOptions, setSanitizeHtmlOptions, extract } from 'article-parser'

const currentConfig = getSanitizeHtmlOptions()
setSanitizeHtmlOptions({
  ...currentConfig,
  allowedAttributes: {
    ...currentConfig.allowedAttributes,
    span: ['data-sheets-value']
  }
})

// test extract function here
```

> impossible to parsing with regex, because each page have different element structures...

RegExp is the rule to group the pages with the same structure. If they have different structure, they need different rules. 
In other case, you can use a regexp for all pages from that domain, then write transformation that cover all variant of structure.

### Problem 2:

> the result from extracted content not completed.

Yes, I've checked and confirm the table has been removed after passing into [`extractWithReadability()` function](https://github.com/ndaidong/article-parser/blob/main/src/utils/parseFromHtml.js#L85).

The extraction process includes 3 steps: run `pre` transformation -->  use readability --> run `post` trantransformation

As I've checked,  missed part has been removed by readability algorithm at the second step. Temporarily we have no way to access this behaviour from `article-parser` inside. So you can create issue on the original package [@mozilla/readability](https://github.com/mozilla/readability) repo (which we are using) and refer back to this issue. Thank you.
