### ISSUE TITLE
is it possible to set timeout for requests?

### ISSUE THREAD

**Issue by harryyuanfeng** [ndaidong/article-parser#31]
how can I set a timeout for requests? like 5 seconds. 

thanks

**Comment by ndaidong** [comment]
@harryyuanfeng not yet. Thanks for your question. I think that feature is needed, and will be implemented in next release.

**Comment by ndaidong** [comment]
@harryyuanfeng : since v1.6.14 you can set the timeout for requests by using .configure() method. It would overwire the default value. For example:

```
var {
  configure,
  extract
} = require('article-parser');

configure({
  timeout: 1e4 // 10 seconds
});

extract(YOUR_URL).then((article) => {
  console.log(article);
}).catch((err) => {
  console.log(err);
});
```
