### ISSUE TITLE
This library is not working for any amazon products.

### ISSUE THREAD

**Issue by awesome1128** [ndaidong/article-parser#312]
Hi Ndaidong.
Nice to meet you!
I hope you're doing great!
You did great job!

But I have one issue, this library doesn't work completely for any amazon products. 
I always keep getting "Failed to fetch" error.
For example , this one.
https://www.amazon.com/Compatible-woednx-Smartwatch-Waterproof-Pedometer/dp/B09MLBFQRC/ref=sr_1_3?keywords=activity+trackers+and+smartwatches&pd_rd_r=dee7e4d8-685b-44ff-82a3-dd79d5f0e4b3&pd_rd_w=OeMRc&pd_rd_wg=yMa2K&pf_rd_p=33f8f65b-b95c-44af-8b89-e59e69e79828&pf_rd_r=NB99R1VJ88AS5D27M72Q&qid=1667427912&qu=eyJxc2MiOiI1LjY3IiwicXNhIjoiNC44MiIsInFzcCI6IjIuNTkifQ%3D%3D&sr=8-3

Can I know why it's not working?
Please let me know.
Thank you! ;)

**Comment by ndaidong** [comment]
@awesome1128 it still works for me. Please try on another server/network to ensure that there is no problem with the connection. Look at the error you got, I guess that the HTTP requests to amazon.com server have been blocked or refused by some security tool.

![Screenshot from 2022-11-03 08-50-25](https://user-images.githubusercontent.com/1809619/199634179-4b83f5da-2ff1-4d86-899e-e41b85e45c33.png)

**Comment by awesome1128** [comment]
Oh nice!
Thank you for your kind reply.
Yeah, I can see there is no image link.
My main goal is to get a main product image url on the product single page.
I think this library fetches title, description and image url from meta tag, right?
If so, I know there is no meta tag for image url.
Can I know is it possible to get a main product image url using your library?
I love to use your library.
Please let me know. 
Thank you again!

**Comment by ndaidong** [comment]
@awesome1128 yes, this lib tries to find image url from meta tag. In this case, there is no twitter card nor open graph meta tags with image url there. I've manually checked HTML source code of the product detail, and found that the slideshow is rendered by JavaScript, the images are loaded by script, so we could not easily to gather them from HTML content.

`article-parser`, as its name shows, just focuses on the article format, such as blog post or news entry. It is not suitable for handling the content like product items on Amazon. I guess that you'll need a particular API, such as [Selling Partner API](https://developer-docs.amazon.com/sp-api/) or [Product Advertising API](https://webservices.amazon.com/paapi5/documentation/), or [some services on RapidAPI](https://rapidapi.com/collection/amazon-products) (?!)

**Comment by awesome1128** [comment]
Hi @ndaidong 
Thank you for your quick and kind reply.
I will review the links you shared.
