### ISSUE TITLE
Incomplete extraction of URL content

### ISSUE THREAD

**Issue by oscaretu** [ndaidong/article-parser#313]
Hello.

I've tried to extract the contents of the URL

https://www.newyorker.com/magazine/2009/06/01/the-cost-conundrum

and I've seen that many paragraphs at the beginning of the article don't appear in the extracted content.

I've tested in https://demos.pwshub.com/article-parser with that URL, and using a CLI program that uses this repository, and the results are incomplete in both cases.

**Comment by ndaidong** [comment]
@oscaretu thank you for your feedback. Let's I investigate the reason why it missed a long part from "Such an arrangement can make..." to the end of article.

**Comment by ndaidong** [comment]
@oscaretu 

It seems that the cause relates to HTML structure of this page. They split the article content into multi parts, each of which is contained within an element with class `body__inner-container`.

![newyorker-original-html-structure](https://user-images.githubusercontent.com/1809619/201504259-366f8cbc-15d6-48b4-a22a-48c3418a8162.png)

You can use [transformation](https://github.com/ndaidong/article-parser#transformation-object) to customize extractor behaviour, as below:

```js
import { extract, addTransformations } from 'article-parser'

addTransformations({
  patterns: [
    /([\w]+.)?newyorker.com\/*/
  ],
  pre: (document) => {
    const els = document.querySelectorAll('.body__inner-container')
    const html = Array.from(els).map(it => it.outerHTML).join('')
    document.body.innerHTML = html
    return document
  }
})

const extractFromUrl = async (url) => {
  try {
    const art = await extract(url)
    console.log(art)
  } catch (err) {
    console.trace(err)
  }
}

extractFromUrl('https://www.newyorker.com/magazine/2009/06/01/the-cost-conundrum')
```

I've tested and the whole article has been extracted.

_without transformation_

![newyorker-no-transformation](https://user-images.githubusercontent.com/1809619/201504434-03338564-9c16-48e8-8f58-8bd0a1ccc34f.png)

_with transformation_

![newyorker-transformation](https://user-images.githubusercontent.com/1809619/201504441-ff5e2393-546b-4bcd-b5fb-38c1e5aacbbe.png)
