### ISSUE TITLE
How to decode these characters?

### ISSUE THREAD

**Issue by mrxf** [ndaidong/article-parser#36]
while the page content isn't English,after use `extract()` method, the `article.content` may like this `&#x7528;&#x2014;&#x2014;&#x6784;&#x5EFA;`.
How can avoid this?

**Comment by ndaidong** [comment]
Could you share to me the URL of that page? I would like to confirm if its HTML source contains these characters.

**Comment by mrxf** [comment]
Like this
http://taobaofed.org/blog/2017/03/09/head-first-typescript/

**Comment by ndaidong** [comment]
Ah, I see. When I try to run a script as below:

```
main.extract('http://taobaofed.org/blog/2017/03/09/head-first-typescript/').then((art) => {
  require('fs').writeFileSync('./test.html', art.content);
});
```
Opening "test.html" give me a good unicode content, not any encoded character even from HTML source:
![screenshot_2017-05-26_18-34-50](https://cloud.githubusercontent.com/assets/1809619/26493381/654b9a82-4243-11e7-80b4-ca634f73436e.png)


If you still want to convert the encoded string like "&#x7528;&#x2014;&#x2014;&#x6784;&#x5EFA;" into human friendly text, you can use something like [he](https://github.com/mathiasbynens/he):

```
var he = require('he');
let s = '&#x7528;&#x2014;&#x2014;&#x6784;&#x5EFA;';
console.log(he.decode(s));
// --> 用——构建
```

Regards,
Dong

**Comment by mrxf** [comment]
Perfectly solved！Thank you!
