### ISSUE TITLE
when dealing with Chinese characters

### ISSUE THREAD

**Issue by harryyuanfeng** [ndaidong/article-parser#37]
When articles contain Chinese, it return content like this:

`'<div> <div><span> </span><span> </span><span> </span><span> </span><div><span> </span><div><span> </span><span> </span><div><span> </span><span> </span>2017&#x5E74;5&#x6708;29&#x65E5; | &#x5206;&#x7C7B;: <a href="http://blog.51.ca/?cat=101" target="_blank">&#x751F;&#x6D3B;</a> (&#x5168;&#x5C40;), <a href="http://blog.51.ca/u-288413/category/%e7%94%9c%e7%82%b9/" target="_blank">&#x751C;&#x70B9;</a>, <a href="http://blog.51.ca/u-288413/category/blogroll/" target="_blank">Blogroll</a> | &#x4F5C;&#x8005;: <a href="http://blog.51.ca/u-288413/author/%e9%99%88%e5%b0%8f%e6%99%93/" target="_blank">&#x9648;&#x5C0F;&#x6653;</a> | <strong>523</strong> &#x6D4F;&#x89C8;<span> </span><div><span> </span><div><p> &#x660E;&#x5929;&#x5C31;&#x662F;&#x7AEF;&#x5348;&#x8282;&#xFF0C; </p><span> </span><p> &#x4FFA;&#x559C;&#x6B22;&#x5403;&#xFF02;&#x67A7;&#x6C34;&#x68D5;&#xFF02;&#xFF0C; </p><span> </span><p> &#x56E0;&#x4E3A;&#x716E;&#x597D;&#x7684;&#x68D5;&#x5B50;&#xFF0C; </p><span> </span><p> &#x8089;&#x8272;&#x91D1;&#x9EC4;&#x900F;&#x660E;&#xFF0C; </p><span> </span><p> &#x8106;&#x53E3;&#x4E0D;&#x817B;&#xFF0C; </p><span> </span><p> &#x5403;&#x65F6;&#x8638;&#x4EE5;&#x767D;&#x7CD6;&#x6216;&#x871C;&#x7CD6;&#xFF0C; </p><span> </span><p> &#x522B;&#x6709;&#x98CE;&#x5473;&#xFF0C;&#x4ECA;&#x5929;&#x505A;&#x4E86;&#x4E00;&#x4E9B;&#x5E94;&#x8282;&#x3002; </p><span> </span><span> </span><p> <img src="http://blog.51.ca/u-288413/files/2017/05/image4.jpg" alt="image.jpg"> </p><span> </span><p> <img src="http://blog.51.ca/u-288413/files/2017/05/image5.jpg" alt="image.jpg"> </p><span> </span><p> <img src="http://blog.51.ca/u-288413/files/2017/05/image6.jpg" alt="image.jpg"> </p><span> </span><span> </span><span> </span></div><span> </span></div><span> </span><span> </span></div><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span><span> </span></div><span> </span><span> </span><span> </span><span> </span></div><span> </span><span> </span></div> </div>'`

is it possible to have content show exact Chinese characters?

**Comment by ndaidong** [comment]
You may need some libs to decode these chars, such as [he](https://www.npmjs.com/package/he). Please give it a try.
