### ISSUE TITLE
1.6.31 breaks parsing wikipedia articles

### ISSUE THREAD

**Issue by davidcameron** [ndaidong/article-parser#41]
I get nothing back when calling `.getArticle` on a Wikipedia article (try https://en.wikipedia.org/wiki/Ramen).

1.6.2 returns `<head>` tags for Wikipedia articles. 1.6.15 works correctly with Wikipedia articles.

**Comment by ndaidong** [comment]
@davidcameron  thanks. I will take a look on this case.

**Comment by ndaidong** [comment]
@davidcameron A script to handle Wikipedia link has been added to v1.6.4, please check if it works for you now.

**Comment by davidcameron** [comment]
This still doesn't seem to work for me, running v1.6.4:

`var fetch = require('node-fetch');
var parser = require('article-parser');
var fs = require('fs');

var articleUrl = 'https://en.wikipedia.org/wiki/Ramen';

fetch(articleUrl)
.then(res => {
    return res.text();
})
.then(html => {
    //console.log('html', html);
	parser.getArticle(html).then(stuff => {
        console.log('done', stuff);
        fs.writeFile('./ramen.html', stuff, function (e) {
            e && console.log('file error', e);
        });
    });

});
`

^ Logs and writes an empty response.

**Comment by ndaidong** [comment]
@davidcameron I think it was resolved with v2.0.0-rc I've just released. Please help me test if it works. Thanks.

**Comment by ndaidong** [comment]
@davidcameron : after a week of testing, it looks like the problem has been resolved as well by v2.x.x, so I would close this issue now. Feel free to reopen if it still not works for you.
