### ISSUE TITLE
latest version show Error: No article extracted. Cancel process.

### ISSUE THREAD

**Issue by harryyuanfeng** [ndaidong/article-parser#45]
"article-parser": "1.6.15" this works fine

but 1.6.4 show that error message when parsing Chinese articles.

**Comment by ndaidong** [comment]
@harryyuanfeng thanks, I would check it. Could you send to me the link of article that caused issue?

**Comment by argjendhaxhiu** [comment]
@ndaidong  This link: http://www.spiegel.de/politik/deutschland/ehe-fuer-alle-was-bedeutet-das-ergebnis-der-abstimmung-im-bundestag-a-1155221.html
and others like:
https://www.youtube.com/watch?v=EXERMOAIyUE (all youtube links)
https://vimeo.com/222111805 (all Vimeo links)

all of them work locally but not in production. What can be the issue?

**Comment by ndaidong** [comment]
@argjendhaxhiu thanks, I'm detecting the issue.

**Comment by ndaidong** [comment]
@harryyuanfeng @argjendhaxhiu  I think the problem has been resolved with v2.0.0-rc I've just released. Please help me test if it works. Thanks.

**Comment by ndaidong** [comment]
@everyone: after a week of testing, it looks like the problem has been resolved as well. So I would close this issue now. Feel free to reopen if it still not works for you.
