### ISSUE TITLE
Error: No article extracted. Cancel process.

### ISSUE THREAD

**Issue by argjendhaxhiu** [ndaidong/article-parser#71]
What is this issue? Is it something that can be solved ?

Btw locally the same url works. The url is this:

http://www.tagesschau.de/ausland/steudtner-prozess-video-105.html

When I try to change in the package the version from "article-parser": "^1.6.15", to "article-parser": "^2.3.2" then I try to run program I get this error:

```
var extract = async (inputURL = '') => {
                    ^

SyntaxError: Unexpected token (
```

**Comment by ndaidong** [comment]
@argjendhaxhiu could you provide a little more about your platform? Which version of Node.js you are using?

**Comment by ndaidong** [comment]
@argjendhaxhiu since v2, it requires node.js v7.6 or higher that understands async/await syntax. You need to upgrade your Node.js or using a docker image with newer node.js version.

**Comment by argjendhaxhiu** [comment]
Locally I have v6.9.2, and is working. For the production, the server is AWS ubuntu !

**Comment by ndaidong** [comment]
@argjendhaxhiu I bed that you are running an older version of article-parser on your local machine.

**Comment by argjendhaxhiu** [comment]
"article-parser": "^1.6.15" / Node v6.9.2 = LOCALLY
"article-parser": "^1.6.15", / Node  v6.11.4 = PRODUCTION

**Comment by ndaidong** [comment]
@argjendhaxhiu ok, I see. So there is no prolem with the package version. But the link from tagesschau.de could not be extracted as expected. I would fix it asap.

**Comment by ndaidong** [comment]
@argjendhaxhiu the good news is the last version of article-parser could extract that link as well. So I still would like to recommend you to upgrade your Node.js platform to the latest version (I mean v8.8.0 for right now) to make use of new great features. Thanks.

![screenshot_2017-10-30_13-38-06](https://user-images.githubusercontent.com/1809619/32157727-eda64e0e-bd77-11e7-9f46-7001216b68e6.png)
