### ISSUE TITLE
Can't parse youtube video inside article

### ISSUE THREAD

**Issue by norrisboat** [ndaidong/article-parser#74]
I can't seem to get the video inside an article:
    
	<p class="text-justify">
		<strong>WATCH VIDEO BELOW</strong>
	</p>
	<p class="text-justify">
		<iframe src="https://www.youtube.com/embed/xxxxxxx" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
	</p>

It can get the WATCH VIDEO BELOW but can't get the iframe. How can I achieve this?

**Comment by ndaidong** [comment]
@norrisboat current version does not support this feature. I'm considering to implement something like that but it's quite complicate and may belong to another tool such as video-extractor.

**Comment by norrisboat** [comment]
Ok keep us posted
