### ISSUE TITLE
htmlRules not being applied to results

### ISSUE THREAD

**Issue by m-leon** [ndaidong/article-parser#78]
Current behavior prevents developers from modifying the htmlRules object used with sanitize-html. Instead the htmlRules that is applied is a constant (config.article.htmlRules) defined in './config/index.js'. This seems to be because of an issue previously with parsing Wikipedia articles (see #41). Issue #41 seems to have been resolved by other commits and this remnant of prevent direct access to the htmlRules seems to serve no purpose that I can see. I will fork and create a pull request.

**Comment by ndaidong** [comment]
Resolved with v2.4.0 
https://gitlab.com/ndaidong/article-parser/merge_requests/79
