### ISSUE TITLE
Is there a way to pass a string holding the HTML instead of just a url?

### ISSUE THREAD

**Issue by extricator** [ndaidong/article-parser#80]
I'm loving this utility, thank you for writing it. However, I'm wondering if there is a way to pass a string holding the HTML document instead of a url pointing to one?

**Comment by ndaidong** [comment]
@extricator thank you for your compliment. Currently, it only accepts a url, not HTML document. I'm considering to add this next release. It's true that in some cases, we have HTML content already, don't need to send another request to retrieve it any more.

**Comment by rpgdev** [comment]
> It's true that in some cases, we have HTML content already, don't need to send another request to retrieve it any more.

What about file URIs pointing to html files? Does it support those?

**Comment by ndaidong** [comment]
@rpgdev I'm not sure. It depends on the way how node-fetch handles the URLs. This lib uses node-fetch to retrieve html content from given URL.

**Comment by ndaidong** [comment]
@extricator this feature has been added since v4, please try and give me the feedback if any. Thanks.
