### ISSUE TITLE
For some articles it's not at all responding

### ISSUE THREAD

**Issue by SkyTreasure** [ndaidong/article-parser#85]
Hi,
I tried parsing certain articles https://www.miamiherald.com/news/state/florida/article236809668.html
its not responding at all. 
Not even erroring out.

In version 3.0.0

**Comment by ndaidong** [comment]
@SkyTreasure thank you, I'm taking a look into this case.

**Comment by ndaidong** [comment]
@SkyTreasure this belong to the way how miamiherald.com accept/refure the requests from outside. I'm not sure, maybe relate to headers. However the problem does not happen with article-parser v4, please try again with [article-parser@4.0.0rc2](https://www.npmjs.com/package/article-parser).

**Comment by SkyTreasure** [comment]
Thanks, yea its working in 4.0.0rc2.
