### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by princesust** [ndaidong/article-parser#97]
It's not working for https://www.aljazeera.com/news/2019/11/china-rule-hk-constitution-mask-ruling-191119004914628.html

**Comment by ndaidong** [comment]
@princesust I've checked this website and found that it has a lot of errors on HTML structure/format which article-parser could not clean and fix from its side. Hopefully the webmasters there will be more interested in HTML5 standards in future.

**Comment by princesust** [comment]
@ndaidong, Thanks a lot for the quick turn around.

**Comment by ndaidong** [comment]
@princesust yes, I tried to normalize the input html code but that doesn't help. Do you have any suggestion?
